Add vultr provider interface methods
kubermatic/machine-controller pull request #1531
Opened 2023-01-12 23:44 UTC by 2000yeshu

Signed-off-by: Yakul Garg <2000yeshu@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2023-01-15 13:10 UTC, 2000yeshu commented
This adds basic support for vultr provider. All vultr API options are not yet supported

2023-02-02 08:32 UTC, lakshmanpasala commented
What's the status of this? Can some one review this soon? This will save a ton of time for me.

2023-02-02 10:41 UTC, igniteram commented
@ahmedwaleedmalik @embik Can you please look into this PR,  this would be great for all Vultr cloud users!

2023-02-04 11:39 UTC, ahmedwaleedmalik commented
@2000yeshu thanks for the awesome contribution. 

We have a similar PR open for Vultr already as well https://github.com/kubermatic/machine-controller/pull/1421. Although it was stalled because we don't have a way to [test this cloud provider](https://github.com/kubermatic/machine-controller/pull/1421#issuecomment-1237955132).

We will discuss this PR internally on Monday hopefully and then proceed with this. Can you please compare your changes with [#1421](https://github.com/kubermatic/machine-controller/pull/1421) to make sure that you are not missing out on any essential configuration etc.

cc @jonatasbaldin @dajudge as consumers of machine-controller you folks might also be interested in this.

2023-02-04 11:39 UTC, ahmedwaleedmalik commented
/ok-to-test

2023-02-04 12:58 UTC, 2000yeshu commented
@ahmedwaleedmalik cross-checked my PR with #1421. I have added one more optional parameter named `osId` compared to that and made changes to the example vultr manifest to show all params.

2023-02-09 16:11 UTC, ahmedwaleedmalik commented
Can you please fix the following failing jobs:
- pull-machine-controller-license-validation 
- pull-machine-controller-lint
- pull-machine-controller-test
- pull-machine-controller-verify-boilerplate 

Disable `pull-machine-controller-e2e-vultr` since we don't have any active account unfortunately to test for that cloud provider.

2023-02-15 09:44 UTC, ahmedwaleedmalik commented
@2000yeshu did you get a chance to take a look on [this](https://github.com/kubermatic/machine-controller/pull/1531#issuecomment-1424446650)?

2023-02-15 11:50 UTC, 2000yeshu commented
Hey @ahmedwaleedmalik, i will fix this tomorrow. Sorry, didnt get a chance to look at this.

2023-02-16 21:40 UTC, 2000yeshu commented
/retest-required

2023-02-16 21:59 UTC, 2000yeshu commented
@ahmedwaleedmalik, have fixed the tests.

2023-02-17 11:38 UTC, ahmedwaleedmalik requested changes
Minor nits

2023-02-17 11:38 UTC, ahmedwaleedmalik commented on pkg/cloudprovider/provider/vultr/provider.go
> +Copyright 2019 The Machine Controller Authors.
```suggestion
Copyright 2023 The Machine Controller Authors.
```

2023-02-17 11:38 UTC, ahmedwaleedmalik commented on pkg/cloudprovider/provider/vultr/provider.go
> +	"k8s.io/apimachinery/pkg/util/sets"
```suggestion
	"github.com/vultr/govultr/v2"
	"golang.org/x/oauth2"
	
	cloudprovidererrors "github.com/kubermatic/machine-controller/pkg/cloudprovider/errors"
	"github.com/kubermatic/machine-controller/pkg/apis/cluster/common"
	clusterv1alpha1 "github.com/kubermatic/machine-controller/pkg/apis/cluster/v1alpha1"
	"github.com/kubermatic/machine-controller/pkg/cloudprovider/instance"
	vultrtypes "github.com/kubermatic/machine-controller/pkg/cloudprovider/provider/vultr/types"
	cloudprovidertypes "github.com/kubermatic/machine-controller/pkg/cloudprovider/types"
	"github.com/kubermatic/machine-controller/pkg/providerconfig"
	providerconfigtypes "github.com/kubermatic/machine-controller/pkg/providerconfig/types"

	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/sets"
```

2023-02-17 11:38 UTC, ahmedwaleedmalik commented on pkg/cloudprovider/provider/vultr/provider.go
> +	ctx := context.Background()
Please propagate context from the parent methods instead of using `context.Background()`.

2023-02-17 11:38 UTC, ahmedwaleedmalik commented on pkg/cloudprovider/provider/vultr/types/types.go
> +Copyright 2019 The Machine Controller Authors.
```suggestion
Copyright 2023 The Machine Controller Authors.
```

2023-02-19 21:40 UTC, 2000yeshu commented
Done

2023-02-20 11:15 UTC, ahmedwaleedmalik approved these changes
/approve
/lgtm

@2000yeshu thank you for this awesome contribution. 🎊

2023-02-20 13:15 UTC, merged