Create workaround for kubelet stopped posting node status bug
kubermatic/machine-controller pull request #844
Opened 2020-11-02 10:34 UTC by phiphi282

**What this PR does / why we need it**:

Sometimes the kubelet suddenly starts to hang and the kubelet needs to be restarted, or even the node if there is no ssh access.
This pr adds a script to cloud init to check the kubelet logs periodically and restarts the kubelet if needed.

This is because of this bug in kubernetes: https://github.com/kubernetes/kubernetes/issues/87615
That will probably be fixed with the first kubernetes version that will use golang 1.16 (probably earliest version will be 1.21).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
We have only tested this for ubuntu, flatcar and coreos.
It is possible that there are some issues with RHEL, SLES and centos.
If there are any e2e tests that should be extended as well then please let me know.

**Optional Release Note**:

```release-note
automatically restart kubelets that stop posting node status
```

2020-11-02 10:36 UTC, phiphi282 commented
/assign @moelsayed

2020-11-02 15:00 UTC, moelsayed commented on pkg/userdata/coreos/testdata/v1.17.0-vsphere-proxy.yaml
> +              output=$(journalctl -u kubelet -n 1 | grep "use of closed network connection")
nit: you might want to use `grep -q`

2020-11-02 15:39 UTC, moelsayed requested changes
Thank you for the PR. I left a few minor comments.
I am assuming, since the script only checks the last line in the logs, kubelet stops completely at this point?
Also, is running this every 10 minutes is enough? Wouldn't the node be unavailable at this point?

@kron4eg what do you think about RHEL/CentOS? Would this be safe?

2020-11-02 15:39 UTC, moelsayed commented on pkg/userdata/helper/kubelet.go
> +    output=$(journalctl -u kubelet -n 1 | grep "use of closed network connection")
nit: Please use `grep -q`

2020-11-02 15:39 UTC, moelsayed commented on pkg/userdata/helper/kubelet.go
> +	return `#!/bin/bash
nit: please use `#!/usr/bin/env bash`

2020-11-02 15:39 UTC, moelsayed commented on pkg/userdata/rhel/provider.go
> +		return "", fmt.Errorf("FAILED TO PARSE USER-DATA TEMPLATE: %V", err)
IDE going haywire?

2020-11-02 15:45 UTC, kron4eg commented
But what about `/etc/systemd/system/kubelet-healthcheck.service` and its `/opt/bin/health-monitor.sh kubelet`? I suppose we can modify health-monitor.sh instead of introducing new scripts (and wasting precious user-data space).

2020-11-03 09:31 UTC, phiphi282 commented on pkg/userdata/rhel/provider.go
> +		return "", fmt.Errorf("FAILED TO PARSE USER-DATA TEMPLATE: %V", err)
Yeah looks like it 😅

2020-11-03 15:53 UTC, kron4eg reviewed
https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/helper/download_binaries_script.go#L88 here it's hardcoded the git revision to download. So after merging this PR the download_binaries_script.go has to be updated too (but only after since the revision is unknown).

2020-11-03 15:53 UTC, kron4eg commented on pkg/userdata/scripts/health-monitor.sh
> +    if [ $failed ]; then
there are no booleans in shell, the `if` body will always evaluate unconditionally.

2021-02-24 12:59 UTC, kron4eg commented
This PR is replaced by the #901

2021-02-24 12:59 UTC, closed without merging